### ISSUE TITLE
Sources Page

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#101]
**Describe the bug**
Some of the names of the databases on the Sources Page are showing up as urls rather than as names.

**To Reproduce**

1. Go to '...'  About
2. Click on '....' Sources
3. Scroll down to '....' Databases

**Expected behavior**
I would expect to see names rather than URLS.

**Screenshots**
 See below

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mojave
 - Browser [e.g. chrome, safari] Chrome

<img width="958" alt="Capture d’écran, le 2021-02-18 à 06 42 01" src="https://user-images.githubusercontent.com/62541441/108373535-db2acf80-71b4-11eb-89d6-e655963d5712.png">

**Comment by ubermichael** [comment]
Those reports have dc.source.url without dc.source. I'll add a check to the validation tools for that (if there is a dc.source.url there must also be a dc.source). But the reports will need to be updated for that. 

Luckily we won't need to retranslate or rematch the the reports.

**Comment by ccolliga** [comment]
I think this issue is fixed now.
