### ISSUE TITLE
Data Sheets -- Accents showing up as Symbols

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#103]
**Describe the bug**
Accents in the data sheets are showing up as symbols.

**To Reproduce**
1. Go to '...' Footer, data page
2. Click on '....' Matching Documents link.
3. See errors on page

**Expected behavior**
I expect the accents to display up as accents.

**Desktop (please complete the following information):**
Mojave, Chrome

<img width="866" alt="Capture d’écran, le 2021-02-18 à 07 23 36" src="https://user-images.githubusercontent.com/62541441/108379119-7a05fa80-71ba-11eb-879c-a2c5c251c658.png">

**Comment by ubermichael** [comment]
The data sheets are encoded in UTF-8. If you use MS Excel to open the CSV files, you must select UTF-8 as an encoding. For some reason Excel defaults to a different encoding even though the rest of the world uses UTF-8 as a standard.

**Comment by ccolliga** [comment]
Thanks, okay.


Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Michael Joyce <notifications@github.com>
Envoyé : jeudi 18 février 2021 21:32
À : sfu-dhil/wilde
Cc : Colette Colligan; Author
Objet : Re: [sfu-dhil/wilde] Data Sheets -- Accents showing up as Symbols (#103)


Closed #103<https://github.com/sfu-dhil/wilde/issues/103>.
