### ISSUE TITLE
Headlines of reports misaligned in safari

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#105]
**Describe the bug**
In Safari, the headlines on individual reports pages are misaligned.  In Chrome, they display correctly.

**To Reproduce**
Use Safari
Go to All Reports
Click on any headline 
See the misalignment of the headline.

**Expected behavior**
I expect the headline to be aligned  with the report text, like displayed in Chrome.

**Screenshots**
<img width="1069" alt="Capture d’écran, le 2021-02-18 à 08 05 33" src="https://user-images.githubusercontent.com/62541441/108389848-ec7bd800-71c4-11eb-91e6-fd270d540ada.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. Mojave
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] 14.0.1

**Comment by ccolliga** [comment]
Also the same issue arises for the translations, in the translation tab, where headline and text all aligned to the 
<img width="439" alt="Capture d’écran, le 2021-02-18 à 08 42 38" src="https://user-images.githubusercontent.com/62541441/108390409-7f1c7700-71c5-11eb-8011-dfd765be25e7.png">
left.

**Comment by joeytakeda** [comment]
I can't replicate the issue on the live site or on my local one. The only difference as far as I can tell is that I'm running Safari 14.0.3, but I don't think that should matter (I think the last digit is only updated for security releases so it shouldn't affect the display).

Can you do a hard-reload (holding shift while clicking refresh) and see if the issue persists?

**Comment by ubermichael** [comment]
I cannot replicate this one either, using the same OS and browser. So I'm closing this one.

**Comment by ccolliga** [comment]
The issue persists for me. Not sure why. I'm running Safari 14.0.1.

**Comment by ccolliga** [comment]
Fixed. When I increase the size of the text the alignment is fine.
