### ISSUE TITLE
Pages not displaying

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#108]
**Describe the bug**
On the Documentation page, the Compare Documents and Compare Paragraphs links open to pages which are not displaying the reports.

**To Reproduce**
1. Go to '...' Footer, Documentation
2. Click on '....' Compare Documents or Compare Oaragraphs
4. See error. See how the reports do not display
https://dhil.lib.sfu.ca/wilde/documentation.html
https://dhil.lib.sfu.ca/wilde/compare-docs.html?a=eja_1688&b=sara_290
https://dhil.lib.sfu.ca/wilde/compare.html?a=eja_1688&b=sara_290

**Expected behavior**
I expect the reports to display.

**Screenshots**
See links above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. Mac Mojave
 - Browser [e.g. chrome, safari]. Chrome

**Comment by ccolliga** [comment]
Here is another link from Documentation that does not show the reports:
https://dhil.lib.sfu.ca/wilde/view.html?f=eja_1688

**Comment by ubermichael** [comment]
The HTML IDs of the reports changed. Do you know which reports those links went to?

**Comment by ccolliga** [comment]
the April 20th, 1895 issue of Adelaide's Evening Journal.<https://dhil.lib.sfu.ca/wilde/view.html?f=eja_1688>



Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Michael Joyce <notifications@github.com>
Envoyé : lundi 22 février 2021 18:57
À : sfu-dhil/wilde
Cc : Colette Colligan; Author
Objet : Re: [sfu-dhil/wilde] Pages not displaying (#108)


The HTML IDs of the reports changed. Do you know which reports those links went to?

**Comment by ccolliga** [comment]
https://dhil.lib.sfu.ca/wilde/view.html?f=teja_358


This is the current URL for the paper


Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Michael Joyce <notifications@github.com>
Envoyé : lundi 22 février 2021 18:57
À : sfu-dhil/wilde
Cc : Colette Colligan; Author
Objet : Re: [sfu-dhil/wilde] Pages not displaying (#108)


The HTML IDs of the reports changed. Do you know which reports those links went to?

**Comment by ubermichael** [comment]
I know the URLs the links went to, but I'm not sure which reports those are. Do you know the newspaper and dates for those links?

**Comment by ccolliga** [comment]
I think this issue is now fixed.


Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Michael Joyce <notifications@github.com>
Envoyé : lundi 22 février 2021 20:46
À : sfu-dhil/wilde
Cc : Colette Colligan; Author
Objet : Re: [sfu-dhil/wilde] Pages not displaying (#108)


I know the URLs the links went to, but I'm not sure which reports those are. Do you know the newspaper and dates for those links?
