### ISSUE TITLE
Newspaper page on site

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#135]
### What isn’t working as expected on the website?

This page is not displaying the names of the newspapers.
https://dhil.lib.sfu.ca/wilde/newspaper.html

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

NA

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/wilde/newspaper.html

### What steps did you take before you encountered the bug?

1.I visited https://dhil.lib.sfu.ca/wilde/newspaper.html
2. I saw that no newspaper names were displaying, just the # of articles.

### What browser, operating system, and device were you using when you encountered the error?

Chrome; Macbook; 12.0.1; also tried on Safari. Same result.

**Comment by ubermichael** [comment]
Fixed by regenerating the cached newspapers page.
