### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#144]
### What isn’t working as expected on the website?

A couple of images from the image gallery are not displaying

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

No error message shown. But when you go to the image gallery, not all the images are displaying properly.
<img width="1280" alt="Capture d’écran, le 2022-04-27 à 19 39 50" src="https://user-images.githubusercontent.com/62541441/165665802-27f5a138-0a2b-414c-a10d-c0cc2815f23b.png">

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/wilde_new/gallery.html

### What steps did you take before you encountered the bug?

I went to https://dhil.lib.sfu.ca/wilde_new/gallery.html
I noticed that the images for L'Echo de Paris December 31 1895 and The San Francisco Examiner
June 3 1895. were missing

### What browser, operating system, and device were you using when you encountered the error?

Chrome; Macbook; 12.0.1

**Comment by ubermichael** [comment]
They're fixed now. You may need to clear your browser cache to pick up the change.
