### ISSUE TITLE
Implement New Version of Documentation

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/wilde#36]
We have just received another draft of the documentation.

**Comment by rcastong** [comment]
Can we discuss how we will approach this? Colette wrote the following:

From: Colette Colligan <ccolliga@sfu.ca> 
Sent: Monday, March 9, 2020 8:36 AM
To: Remi Castonguay <remi_castonguay@sfu.ca>
Subject: Wilde Documentation

Dear Remi,

I revised the Wilde documentation since I last looked at what Kim sent me. I made some silent changes to the text and then track changed anything substantive. I deleted text that is no longer relevant since Michael removed the cosine matching. The description of how the comparison tools work on the Individual reports pages still needs work, though. If you accept the changes/comments I have made and Kim made earlier, I can continue to clean up the text for you then to pass on to a fellow or someone else to add to/review.

https://docs.google.com/document/d/1TS9al6K0N9gZ8hM3Uf7f1B8DVRB_v7-w5ZScY8XSNEM/edit?usp=sharing 

Best, Colette

**Comment by ubermichael** [comment]
Edited to remove the email addresses and the direct link to edit the documentation document.

**Comment by rcastong** [comment]
@ubermichael Could you take a look today at the outstanding items in the Wilde documentation?

**Comment by ubermichael** [comment]
I have resolved the issues in the documentation.

**Comment by rcastong** [comment]
Thx, @ubermichael !

**Comment by joeytakeda** [comment]
Documentation updated in https://github.com/joeytakeda/wilde/commit/04c8dd518de083b686cd92729f75fc4176eafb2f and pushed to the live site (at `/manual.html`)

**Comment by michael-joyce** [comment]
I think we can call this one complete. Thanks @joeytakeda
