### ISSUE TITLE
Reports pages (slow to display)

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#45]
The new Newspaper page is slow to open (~more than 10 seconds), and remains an issue. The other pages added to reports display more quickly (though they can be slightly slow to display).

**Comment by ubermichael** [comment]
It's about six seconds for me. There isn't a whole lot to be done to speed this up. To build the page the server has to look at each of the 1400 reports and extract the necessary information. That's going to take time, and it's just going to get worse when we add the next batch of reports.

The only thing to be done is to generate a static cache of that page like we already did for the full list of reports. But even that page is still slow to load.
