### ISSUE TITLE
Report graph is broken

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/wilde#47]
**Describe the bug**
The graph on the reports page doesn't show the lines, only the legend.

**To Reproduce**
1. Go to the reports page
1. Wait for the graph to load
1. The lines never load 

**Expected behavior**
The graph should show the lines.

**Screenshots**
(Firefox on left; Chrome on right)

![Screen Shot 2020-04-29 at 11 51 03 AM](https://user-images.githubusercontent.com/17664763/80634716-bd1a9580-8a0f-11ea-8c03-1a58382892a9.png)

The error from the console is:

```
TypeError: d.values[lastHoveredBarIndex] is undefined d3.stacked.bar.js:458:38
    tooltipContent https://dhil.lib.sfu.ca/wilde/resources/js/d3.stacked.bar.js:458
    each https://dhil.lib.sfu.ca/wilde/resources/lib/d3/d3.min.js:3
    Y https://dhil.lib.sfu.ca/wilde/resources/lib/d3/d3.min.js:1
    each https://dhil.lib.sfu.ca/wilde/resources/lib/d3/d3.min.js:3
    tooltipContent https://dhil.lib.sfu.ca/wilde/resources/js/d3.stacked.bar.js:457
    showTooltip https://dhil.lib.sfu.ca/wilde/resources/js/d3.stacked.bar.js:444
    $/< https://dhil.lib.sfu.ca/wilde/resources/lib/d3/d3.min.js:1

```

**Desktop (please complete the following information):**
FF 74; Chrome 80.0.3987.163 on Mojave 10.14.6.

**Additional context**

If page load is a concern, I think all of the Javascript on the page should be removed, including the filtering features on the page to make the page as simple as possible. It will still take time to render and load, but it should cut it down.

**Comment by ubermichael** [comment]
This page needs to be completely removed. The other browsing options are in place to take its place.
