### ISSUE TITLE
Problem with display of Image Gallery

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#50]
**Describe the bug**

The Image gallery is not displaying correctly. When I view the page in Safari and in Chrome, some images are displaying twice. In Safari, moreover, the image cards are not displaying in a uniform way.

**To Reproduce**
1. Go to '...'     Wilde Trials Home page
2. Click on '....'  About
3. Scroll down to '....'  Image Gallery
4. See error. 

**Expected behavior**
I expect the page to show a uniform grid of cards and not to display some of these images in duplicate.

**Screenshots**

<img width="677" alt="Image gallery in safari" src="https://user-images.githubusercontent.com/62541441/82841771-19949780-9e8c-11ea-90cd-5fc9b64b9756.png">
<img width="911" alt="image gallery in Chrome" src="https://user-images.githubusercontent.com/62541441/82841777-1f8a7880-9e8c-11ea-84e7-8399263eeb82.png">

**Desktop (please complete the following information):**
  Mojave 10.14.6
  Chrome & Safari

**Additional context**

**Comment by ubermichael** [comment]
This is really two separate bugs. I've fixed the duplicate image problem. I'm not sure about the other one. I can't see any problem with how the cards are displayed.

**Comment by joeytakeda** [comment]
@ubermichael I can deal with the card grid thing--I've encountered similar issues before since Safari's understanding of `flex-grow` seems to be different from Chrome and Firefox.

**Comment by ubermichael** [comment]
I've got a fix now, but for some reason eXist doesn't want to accept it.
