### ISSUE TITLE
Image Gallery Bug

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#51]
**Describe the bug**
Three images -- from The Paris Herald -- are not displaying the right title and are missing the description that goes with them. Is it because 

**To Reproduce**
1. Go to 'Home Page'
2. Select 'About'
3. Select "Image Gallery"
4. Scroll down to Paris Herald Images

**Expected behavior**
I expect for the titles for these three images to look like the titles under the other images. There should also be descriptive text with these images.

**Screenshots**

<img width="965" alt="Capture d’écran, le 2020-05-30 à 12 26 40" src="https://user-images.githubusercontent.com/62541441/83337561-68b64000-a271-11ea-9b00-b80161ef13f6.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OSMojave 10.14.6
 - Browser [e.g. chrome, safari]. Chrome & Safari

**Comment by ccolliga** [comment]
Note that I also added two additional images to the Vault folder called Wilde Images and updated the xml file in it called Images. I can add this to a future reminder to update the images, but thought I would add this here in case you need to work with the images xml file in Vault.

**Comment by ubermichael** [comment]
I rebuilt the image gallery. It should be OK now.
