### ISSUE TITLE
Data page

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#58]
**Describe the bug**
Some of the csv files on the data page are not downloading or are missing content. Those not downloading are the "Matching documents" and the "Matching paragraphs." I think the data fields also need to be updated, as match type is no longer relevant as everything is Levenshtein. The file missing content is the last one "Gephi paper matches."

**To Reproduce**
1. Go to 'Data (footer)
2. Click on 'Matching Documents link or Matching paragraphs link or the "Paper matches" link
4. See error "Cette page de fonctionne pas"

**Expected behavior**
When I select these links to files, I expect them to be able to open and download them.

**Screenshots**
<img width="793" alt="Capture d’écran, le 2020-05-30 à 21 51 05" src="https://user-images.githubusercontent.com/62541441/83344751-cbcec380-a2bf-11ea-981b-148606c274ee.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs Mojave 10.14.6
 - Browser [e.g. chrome, safari]. Chrome

**Comment by ubermichael** [comment]
I don't think we're going to get the Matching Documents or Matching Paragraphs to work now. There's simply too much data to generate the export CSVs and the requests are timing out. I'll see if I can generate them manually, but it isn't promising.

The document match CSV file will probably be around 3600 rows, for example. And the paragraph match CSV will likely be 30,000 rows.
