### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#90]
**Describe the bug**
There is an image missing from the Contributors page

**To Reproduce**
1. Go to '...' About
2. Click on '....' Contributors
3. See error

**Expected behavior**
I expect to see an image.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]             Mojave 10.14.6
 - Browser [e.g. chrome, safari].  Chrome
 

<img width="1195" alt="Capture d’écran, le 2020-10-17 à 12 35 02" src="https://user-images.githubusercontent.com/62541441/96352081-75e39800-1075-11eb-89fa-26d6d9a2e681.png">

**Comment by joeytakeda** [comment]
Hi @ccolliga : the image appears for me (screenshot below; this in mobile chrome). 

Can you do a hard refresh (shift + refresh) on the page and see if that clears things up? 

![8EF0B471-8EF6-4E53-A2C9-7B0F928C7131](https://user-images.githubusercontent.com/17664763/96352737-7e8a9d00-107a-11eb-98c5-271d55a0e7b7.jpeg)

**Comment by ccolliga** [comment]
Looks good.


Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Joey Takeda <notifications@github.com>
Envoyé : samedi 17 octobre 2020 22:33
À : sfu-dhil/wilde
Cc : Colette Colligan; Mention
Objet : Re: [sfu-dhil/wilde] Image missing (#90)


Hi @ccolliga<https://github.com/ccolliga> : the image appears for me (screenshot below; this in mobile chrome).

Can you do a hard refresh (shift + refresh) on the page and see if that clears things up?

[8EF0B471-8EF6-4E53-A2C9-7B0F928C7131]<https://user-images.githubusercontent.com/17664763/96352737-7e8a9d00-107a-11eb-98c5-271d55a0e7b7.jpeg>
