### ISSUE TITLE
Alphabetization of Newspaper Titles

### ISSUE THREAD

**Issue by ccolliga** [sfu-dhil/wilde#94]
**Is your feature request related to a problem? Please describe.**

Newspaper titles sometimes begin with an article (such as "the in English, or Le in French) and sometimes don't. It is practice to maintain the article in the title when naming and citing them. Therefore I have tried to do so. But, this makes alphabetization an issue, as lots of papers get alphabetized, and therefore slower to find, by their article. A number of the Wilde site pages involve some kind of alphabetization of the newspaper titles, and so this is an issue that affects a number of pages.

**Describe the solution you'd like**

Could we alphabetize the newspaper titles by the first name in the title following the article. 

**Describe alternatives you've considered**

Not sure what alternatives there are.

**Additional context**

I have provided screenshots of sites in French and English that deal with this issue (in different ways).

<img width="1143" alt="Capture d’écran, le 2021-01-16 à 15 50 56" src="https://user-images.githubusercontent.com/62541441/104827524-6f4ef300-5813-11eb-860e-76088bb477bf.png">

<img width="1131" alt="Capture d’écran, le 2021-01-16 à 16 00 13" src="https://user-images.githubusercontent.com/62541441/104827603-3e22f280-5814-11eb-9dcd-bbbebefde284.png">

**Comment by ubermichael** [comment]
There is probably something useful I can do here. @ccolliga can you provide a list of initial articles to ignore for each of the languages?

**Comment by ccolliga** [comment]
Hi Michael,


Thanks!


English

The


French

Le

La

L'

Les


Spanish

La

El

Los. (Watch out! Does not count for Los Angeles Times)

Las


Italian

La

Il

L'

Gli



German


None to worry about


Dr. Colette Colligan, Professor of English

Simon Fraser University, Canada

Resident Fellow, Paris Institute of Advanced Studies (2019-2020)



________________________________
De : Michael Joyce <notifications@github.com>
Envoyé : mardi 26 janvier 2021 20:56
À : sfu-dhil/wilde
Cc : Colette Colligan; Mention
Objet : Re: [sfu-dhil/wilde] Alphabetization of Newspaper Titles (#94)


There is probably something useful I can do here. @ccolliga<https://github.com/ccolliga> can you provide a list of initial articles to ignore for each of the languages?

**Comment by ubermichael** [comment]
Now that sfu-dhil/alfred#5 is done, this should be possible.
